version: "3"
services:
  drone_operator_1:
    image: registry.waraps.org/waraps-drone-operator:latest
    # image: drone_operator_1:latest
    restart: unless-stopped
    ports:
      - 5000:5000
    volumes:
      - ./data:/app/data
      #- ./:/app
    env_file:
      - .env
    healthcheck:
      test: curl --fail http://localhost:5000 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
